from src.gestorAplicacion.serviciosOfrecidos.TipoObjetivo import TipoObjetivo
from src.gestorAplicacion.serviciosOfrecidos.TipoTerapia import TipoTerapia
from src.gestorAplicacion.sujeto.Restriccion import Restriccion

class Ejercicio:

    _ejercicios_totales = []
    _cantidad_ejercicios = 0

    def __init__(self, nombre, tipoTerapia, tipoObjetivo, restriccion):

        self._nombre = nombre
        self._tipoTerapia = tipoTerapia
        self._tipoObjetivo = tipoObjetivo
        self._restriccion = restriccion

        Ejercicio._cantidad_ejercicios += 1
        self._id = Ejercicio._cantidad_ejercicios

        Ejercicio._ejercicios_totales.append(self)

    def __str__(self):
        return self._nombre

    #Getters

    def get_tipoTerapia(self):
        return self._tipoTerapia
    
    def get_tipoObjetivo(self):
        return self._tipoObjetivo
    
    def get_restriccion(self):
        return self._restriccion
    
    def get_id(self):
        return self._id
    
    def get_nombre(self):
        return self._nombre
    
    @staticmethod
    def get_ejercicios_totales():
        return Ejercicio._ejercicios_totales
    
    #Setters

    def set_tipoTerapia(self, tipoTerapia):
        self._tipoTerapia = tipoTerapia
    
    def set_tipoObjetivo(self, tipoObjetivo):
        self._tipoObjetivo = tipoObjetivo
    
    def set_restriccion(self, restriccion):
        self._restriccion = restriccion
    
    def set_id(self, id):
        self._id = id

    def set_id(self, nombre):
        self._nombre = nombre


# Casos de prueba

ZANCADAS =  Ejercicio("ZANCADAS", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.FUERZA)
HIP_THRUST =  Ejercicio("HIP_THRUST", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.FUERZA)
SENTADILLA_BULGARA =  Ejercicio("SENTADILLA_BULGARA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.FUERZA)
SENTADILLA_SUMO =  Ejercicio("SENTADILLA_SUMO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.FUERZA)
PRENSA =  Ejercicio("PRENSA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.FUERZA)
EXTENSION_CUADRICEPS_ARRIBA =  Ejercicio("EXTENSION_CUADRICEPS_ARRIBA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.EQUILIBRIO)
EXTENSION_CUADRICEPS_ABAJO =  Ejercicio("EXTENSION_CUADRICEPS_ABAJO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.EQUILIBRIO)
HIP_ABDUCTOR_INTERNO =  Ejercicio("HIP_ABDUCTOR_INTERNO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.EQUILIBRIO)
HIP_ABDUCTOR_EXTERNO =  Ejercicio("HIP_ABDUCTOR_EXTERNO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.EQUILIBRIO)
ZANCADA_UNILATERAL =  Ejercicio("ZANCADA_UNILATERAL", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.EQUILIBRIO)
MARIPOSA =  Ejercicio("MARIPOSA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.FLEXIBILIDAD)
PINZA_DE_PIE =  Ejercicio("PINZA_DE_PIE", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.FLEXIBILIDAD)
TRIANGULO_EXTENDIDO =  Ejercicio("TRIANGULO_EXTENDIDO",TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.FLEXIBILIDAD)
RUEDA =  Ejercicio("RUEDA",TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.FLEXIBILIDAD)
LOTO_ELEVADO =  Ejercicio("LOTO_ELEVADO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.FLEXIBILIDAD)
LATERAL_INTENSO =  Ejercicio("LATERAL_INTENSO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.FLEXIBILIDAD)
ARADO =  Ejercicio("ARADO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.CARDIOVASCULAR)
CURL_DE_BICEPS =  Ejercicio("CURL_DE_BICEPS", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.CARDIOVASCULAR)
NATACION_EXPUESTA =  Ejercicio("NATACION_EXPUESTA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.CARDIOVASCULAR)
BRAZADAS_LATERALES =  Ejercicio("BRAZADAS_LATERALES", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.CARDIOVASCULAR)
BRAZADAS_TRASERAS =  Ejercicio("BRAZADAS_TRASERAS", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.CARDIOVASCULAR)
CARRERA_MEDIA =  Ejercicio("CARRERA_MEDIA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.CARDIOVASCULAR)
EXTENSION_PISCINA =  Ejercicio("EXTENSION_PISCINA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.RESPIRATORIA)
CARRERA_PESO =  Ejercicio("CARRERA_PESO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.RESPIRATORIA)
FLEXIONES_DIAMANTE =  Ejercicio("FLEXIONES_DIAMANTE", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.RESPIRATORIA)
ESTIRAMIENTO_CRUZADO =  Ejercicio("ESTIRAMIENTO_CRUZADO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.RESPIRATORIA)
ESTIRAMIENTO_PIERNA_LATERAL =  Ejercicio("ESTIRAMIENTO_PIERNA_LATERAL", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.FORTALECIMIENTO_MUSCULAR, Restriccion.RESPIRATORIA)
PRESS_DE_PECHO_CON_CABLE =  Ejercicio("PRESS_DE_PECHO_CON_CABLE", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.FUERZA)
PRESS_DE_BANCA_CON_AGARRE_CERRADO =  Ejercicio("PRESS_DE_BANCA_CON_AGARRE_CERRADO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.FUERZA)
PRESS_DE_BANCA_CON_PIERNAS_ARRIBA =  Ejercicio("PRESS_DE_BANCA_CON_PIERNAS_ARRIBA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.FUERZA)
PRESS_DE_BANCA_DECLINADO =  Ejercicio("PRESS_DE_BANCA_DECLINADO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.FUERZA)
ROTACION_INCLINADA =  Ejercicio("ROTACION_INCLINADA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.EQUILIBRIO)
ROTACION_EXTERNA =  Ejercicio("ROTACION_EXTERNA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.EQUILIBRIO)
ELEVACION_FRONTAL_CON_BARRA =  Ejercicio("ELEVACION_FRONTAL_CON_BARRA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.EQUILIBRIO)
REMO_POSTERIOR_SIN_BARRA =  Ejercicio("REMO_POSTERIOR_SIN_BARRA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.EQUILIBRIO)
REMO_INTERIOR_SIN_BARRA =  Ejercicio("REMO_INTERIOR_SIN_BARRA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.EQUILIBRIO)
ESTIRAMIENTO_POSTERIOR_CON_BARRA =  Ejercicio("ESTIRAMIENTO_POSTERIOR_CON_BARRA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.FLEXIBILIDAD)
REMO_INTERIOR_CON_BARRA =  Ejercicio("REMO_INTERIOR_CON_BARRA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.FLEXIBILIDAD)
REMO_ELASTICO_CON_BARRA =  Ejercicio("REMO_ELASTICO_CON_BARRA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.FLEXIBILIDAD)
REMO_HORIZONTAL_CONBARRA =  Ejercicio("REMO_HORIZONTAL_CONBARRA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.FLEXIBILIDAD)
ESTIRAMIENTO_INTERIOR_CON_BARRA =  Ejercicio("ESTIRAMIENTO_INTERIOR_CON_BARRA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.FLEXIBILIDAD)
ALARGAMIENTO_CON_POLEA =  Ejercicio("ALARGAMIENTO_CON_POLEA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.CARDIOVASCULAR)
EXTENSION_CON_PESO =  Ejercicio("EXTENSION_CON_PESO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.CARDIOVASCULAR)
EXTENSION_SIMPLE =  Ejercicio("EXTENSION_SIMPLE", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.CARDIOVASCULAR)
ALARGAMIENTO_COMPUESTO =  Ejercicio("ALARGAMIENTO_COMPUESTO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.CARDIOVASCULAR)
EXTENSION_PECHO =  Ejercicio("EXTENSION_PECHO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.CARDIOVASCULAR)
ALARGAMIENTO_EN_MOVIMIENTO =  Ejercicio("ALARGAMIENTO_EN_MOVIMIENTO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.RESPIRATORIA)
EXTENSION_POLEA =  Ejercicio("EXTENSION_POLEA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.RESPIRATORIA)
CARDIO_DE_TENSION =  Ejercicio("CARDIO_DE_TENSION", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.RESPIRATORIA)
EXTENSION_LATERAL_EN_PISCINA =  Ejercicio("EXTENSION_LATERAL_EN_PISCINA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.RESPIRATORIA)
ELEVACION_ALTA =  Ejercicio("ELEVACION_ALTA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_ELASTICIDAD, Restriccion.RESPIRATORIA)
CARRERA_MEDIA_PESO =  Ejercicio("CARRERA_MEDIA_PESO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.FUERZA)
CARRERA_LARGA_PESO =  Ejercicio("CARRERA_LARGA_PESO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.FUERZA)
SALTO_CON_AGARRE =  Ejercicio("SALTO_CON_AGARRE", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.FUERZA)
ELEVACION_PIERNAS_EXTERNO =  Ejercicio("ELEVACION_PIERNAS_EXTERNO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.FUERZA)
ELEVACION_PIERNAS_INTERNO =  Ejercicio("ELEVACION_PIERNAS_INTERNO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.FUERZA)
ELEVACION_PIERNAS_SOBRE_BARRA =  Ejercicio("ELEVACION_PIERNAS_SOBRE_BARRA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.EQUILIBRIO)
ESTIRAMIENTO_SOBRE_BARRA =  Ejercicio("ESTIRAMIENTO_SOBRE_BARRA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.EQUILIBRIO)
EXTENSION_CUADRICEP_FEMORAL =  Ejercicio("EXTENSION_CUADRICEP_FEMORAL", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.EQUILIBRIO)
ELEVACION_CON_UNA_PIERNA =  Ejercicio("ELEVACION_CON_UNA_PIERNA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.EQUILIBRIO)
VELOCIDAD_SOBRE_BARRA =  Ejercicio("VELOCIDAD_SOBRE_BARRA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.EQUILIBRIO)
ESTIRAMIENTO_COMPLETO =  Ejercicio("ESTIRAMIENTO_COMPLETO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.FLEXIBILIDAD)
APERTURA_LATERAL =  Ejercicio("APERTURA_LATERAL", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.FLEXIBILIDAD)
ESTIRAMIENTO_MEDIO =  Ejercicio("ESTIRAMIENTO_MEDIO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.FLEXIBILIDAD)
ELEVACION_CADERAS =  Ejercicio("ELEVACION_CADERAS", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.FLEXIBILIDAD)
EXTENSION_DE_DOMINIO =  Ejercicio("EXTENSION_DE_DOMINIO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.FLEXIBILIDAD)
CARRERA_ALTA_VELOCIDAD =  Ejercicio("CARRERA_ALTA_VELOCIDAD", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.CARDIOVASCULAR)
CARRERA_DE_EXTENSION =  Ejercicio("CARRERA_DE_EXTENSION", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.CARDIOVASCULAR)
CARRERA_ACELERACION_COMPUESTA =  Ejercicio("CARRERA_ACELERACION_COMPUESTA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.CARDIOVASCULAR)
CARRERA_ACELERACION_CONTINUA =  Ejercicio("CARRERA_ACELERACION_CONTINUA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.CARDIOVASCULAR)
CARRERA_VELOCIDAD_COMPLEMENTARIA =  Ejercicio("CARRERA_VELOCIDAD_COMPLEMENTARIA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.CARDIOVASCULAR)
CARRERA_EN_PISCINA =  Ejercicio("CARRERA_EN_PISCINA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.RESPIRATORIA)
TENSION_EN_PISCINA =  Ejercicio("TENSION_EN_PISCINA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.RESPIRATORIA)
CARRERA_PROFUNDA =  Ejercicio("CARRERA_PROFUNDA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.RESPIRATORIA)
CARRERA_DE_CONTENCION =  Ejercicio("CARRERA_DE_CONTENCION", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.RESPIRATORIA)
BARRERAS_VELOCIDAD =  Ejercicio("BARRERAS_VELOCIDAD", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.INCREMENTO_VELOCIDAD, Restriccion.RESPIRATORIA)
ARBOL_CON_PESO =  Ejercicio("ARBOL_CON_PESO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.FUERZA)
EXTENSION_LATERAL_CON_PESO =  Ejercicio("EXTENSION_LATERAL_CON_PESO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.FUERZA)
EXTENSION_CON_PESO_SOBRE_BARRA =  Ejercicio("EXTENSION_CON_PESO_SOBRE_BARRA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.FUERZA)
EXTENSION_CON_PESO_SOBRE_BARRA_INCLINADA =  Ejercicio("EXTENSION_CON_PESO_SOBRE_BARRA_INCLINADA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.FUERZA)
CAMINATA_SOBRE_BARRA =  Ejercicio("CAMINATA_SOBRE_BARRA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.FUERZA)
AGARRE_UNA_MANO =  Ejercicio("AGARRE_UNA_MANO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.EQUILIBRIO)
GIRO_UN_PIE =  Ejercicio("GIRO_UN_PIE", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.EQUILIBRIO)
PIRAMIDE_SOBRE_BARRA_UN_PIE =  Ejercicio("PIRAMIDE_SOBRE_BARRA_UN_PIE", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.EQUILIBRIO)
POLEA_UNA_PIERNA =  Ejercicio("POLEA_UNA_PIERNA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.EQUILIBRIO)
MONTANA_UNA_MANO_UNA_PIERNA =  Ejercicio("MONTANA_UNA_MANO_UNA_PIERNA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.EQUILIBRIO)
ALARGAMIENTO_UNA_PIERNA_EXTERNO =  Ejercicio("ALARGAMIENTO_UNA_PIERNA_EXTERNO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.FLEXIBILIDAD)
ALARGAMIENTO_UNA_PIERNA_INTERNO =  Ejercicio("ALARGAMIENTO_UNA_PIERNA_INTERNO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.FLEXIBILIDAD)
ELEVACION_PIERNAS_BARRA =  Ejercicio("ELEVACION_PIERNAS_BARRA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.FLEXIBILIDAD)
EXTENSION_UNA_PIERNA_EN_BARRA =  Ejercicio("EXTENSION_UNA_PIERNA_EN_BARRA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.FLEXIBILIDAD)
ELEVACION_CON_DISCO_OLIMPICO =  Ejercicio("ELEVACION_CON_DISCO_OLIMPICO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.FLEXIBILIDAD)
EQUILIBRIO_EN_BARRA_ALTA =  Ejercicio("EQUILIBRIO_EN_BARRA_ALTA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.CARDIOVASCULAR)
ELEVACION_EN_BARRA_LATERAL =  Ejercicio("ELEVACION_EN_BARRA_LATERAL", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.CARDIOVASCULAR)
CARRERA_BARRA_UN_PIE =  Ejercicio("CARRERA_BARRA_UN_PIE", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.CARDIOVASCULAR)
INCLINACION_CON_DISCO_OLIMPICO =  Ejercicio("INCLINACION_CON_DISCO_OLIMPICO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.CARDIOVASCULAR)
INCLINACION_TRASERA_CON_DISCOOLIMPICO =  Ejercicio("INCLINACION_TRASERA_CON_DISCOOLIMPICO", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.CARDIOVASCULAR)
ELEVACION_UN_PIE_PISCINA =  Ejercicio("ELEVACION_UN_PIE_PISCINA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.RESPIRATORIA)
INCLINACION_EN_PISCINA =  Ejercicio("INCLINACION_EN_PISCINA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.RESPIRATORIA)
EQUILIBRIO_EN_POLEA =  Ejercicio("EQUILIBRIO_EN_POLEA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.RESPIRATORIA)
CONTENCION_UNA_MANO_PISCINA =  Ejercicio("CONTENCION_UNA_MANO_PISCINA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.RESPIRATORIA)
CARRERA_LARGA_PISCINA =  Ejercicio("CARRERA_LARGA_PISCINA", TipoTerapia.ACONDICIONAMIENTO, TipoObjetivo.MEJORA_DEL_EQUILIBRIO, Restriccion.RESPIRATORIA)
RECUPERACION_ACTIVA_POLEA =  Ejercicio("RECUPERACION_ACTIVA_POLEA", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.FUERZA)
RECUEPACION_ACTIVA_MANCUERNAS =  Ejercicio("RECUEPACION_ACTIVA_MANCUERNAS", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.FUERZA)
RECUPERACION_ACTIVA_DISCOS_OLIMPICOS =  Ejercicio("RECUPERACION_ACTIVA_DISCOS_OLIMPICOS", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.FUERZA)
RECUPERACION_ACTIVA_TENSION =  Ejercicio("RECUPERACION_ACTIVA_TENSION", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.FUERZA)
RECUPERACION_ROPA_DE_COMPRESION =  Ejercicio("RECUPERACION_ROPA_DE_COMPRESION", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.FUERZA)
RECUPERACION_UNILATERAL =  Ejercicio("RECUPERACION_UNILATERAL", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.EQUILIBRIO)
RECUPERACION_EN_BARRA_DE_EQUILIBRIO =  Ejercicio("RECUPERACION_EN_BARRA_DE_EQUILIBRIO", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.EQUILIBRIO)
INCLINACION_MUSCULAR =  Ejercicio("INCLINACION_MUSCULAR", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.EQUILIBRIO)
SOPORTE_BARRA =  Ejercicio("SOPORTE_BARRA", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.EQUILIBRIO)
SOPORTE_COMPRESION =  Ejercicio("SOPORTE_COMPRESION", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.EQUILIBRIO)
REHABILITACION_ESTIRAMIENTO_COMPLETO =  Ejercicio("REHABILITACION_ESTIRAMIENTO_COMPLETO", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.FLEXIBILIDAD)
REHABILITACION_DE_EXTENSION_COMPLETA =  Ejercicio("REHABILITACION_DE_EXTENSION_COMPLETA", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.FLEXIBILIDAD)
REHABILITACION_ALARGAMIENTO_SIN_SOPORTE =  Ejercicio("REHABILITACION_ALARGAMIENTO_SIN_SOPORTE", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.FLEXIBILIDAD)
FISIOTERAPIA_CON_EXTENSION =  Ejercicio("FISIOTERAPIA_CON_EXTENSION", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.FLEXIBILIDAD)
EXTENSION_ALTA =  Ejercicio("EXTENSION_ALTA", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.FLEXIBILIDAD)
FISIOTERAPIA_CONTROLADA =  Ejercicio("FISIOTERAPIA_CONTROLADA", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.CARDIOVASCULAR)
CARRERA_CONTROLADA_CON_PESO =  Ejercicio("CARRERA_CONTROLADA_CON_PESO", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.CARDIOVASCULAR)
RECUPERACION_DE_PASO =  Ejercicio("RECUPERACION_DE_PASO", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.CARDIOVASCULAR)
TERAPIA_DE_MOVILIDAD_COMPLETA =  Ejercicio("TERAPIA_DE_MOVILIDAD_COMPLETA", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.CARDIOVASCULAR)
HIDROTERAPIA_DE_TENSION =  Ejercicio("HIDROTERAPIA_DE_TENSION", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.CARDIOVASCULAR)
HIDROTERAPIA_DE_ONDAS =  Ejercicio("HIDROTERAPIA_DE_ONDAS", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.RESPIRATORIA)
RECUPERACION_PIERNAS_PISCINA =  Ejercicio("RECUPERACION_PIERNAS_PISCINA", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.RESPIRATORIA)
RECUPERACION_EN_PROFUNDIDAD =  Ejercicio("RECUPERACION_EN_PROFUNDIDAD", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.RESPIRATORIA)
HIDROTERAPIA_DE_COMPRESION =  Ejercicio("HIDROTERAPIA_DE_COMPRESION", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.RESPIRATORIA)
RECUPERACION_ACTIVA_PISCINA =  Ejercicio("RECUPERACION_ACTIVA_PISCINA", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_MUSCULAR, Restriccion.RESPIRATORIA)
FORTALECIMIENTO_ARTICULACION_MANCUERNAS =  Ejercicio("FORTALECIMIENTO_ARTICULACION_MANCUERNAS", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.FUERZA)
FORTALECIMIENTO_ARTICULACION_POLEA =  Ejercicio("FORTALECIMIENTO_ARTICULACION_POLEA", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.FUERZA)
FORTALECIMIENTO_ARTICULACION_DISCOS_OLIMPICOS =  Ejercicio("FORTALECIMIENTO_ARTICULACION_DISCOS_OLIMPICOS", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.FUERZA)
RECUPERACION_OSEA_PESO =  Ejercicio("RECUPERACION_OSEA_PESO", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.FUERZA)
RECUPERACION_OSEA_PESO_ELEVADO =  Ejercicio("RECUPERACION_OSEA_PESO_ELEVADO", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.FUERZA)
INCLINACION_CON_BARRA =  Ejercicio("INCLINACION_CON_BARRA", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.EQUILIBRIO)
ELEVACION_DE_PIERNA =  Ejercicio("ELEVACION_DE_PIERNA", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.EQUILIBRIO)
TENSION_EN_BARRA =  Ejercicio("TENSION_EN_BARRA", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.EQUILIBRIO)
TENSION_EN_ARTICULACION_BARRA =  Ejercicio("TENSION_EN_ARTICULACION_BARRA", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.EQUILIBRIO)
ESTIRAMIENTO_COMPLETO_ARTICULACION =  Ejercicio("ESTIRAMIENTO_COMPLETO_ARTICULACION", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.FLEXIBILIDAD)
ESTIRAMIENTO_PARCIAL_ARTICULACION =  Ejercicio("ESTIRAMIENTO_PARCIAL_ARTICULACION", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.FLEXIBILIDAD)
AMPLITUD_SIN_SOPORTE =  Ejercicio("AMPLITUD_SIN_SOPORTE", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.FLEXIBILIDAD)
AMPLITUD_CON_SOPORTE =  Ejercicio("AMPLITUD_CON_SOPORTE", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.FLEXIBILIDAD)
CIRCUITO_PARCIAL =  Ejercicio("CIRCUITO_PARCIAL", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.CARDIOVASCULAR)
CIRCUITO_COMPLETO =  Ejercicio("CIRCUITO_COMPLETO", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.CARDIOVASCULAR)
RECORRIDO_CON_TENSION =  Ejercicio("RECORRIDO_CON_TENSION", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.CARDIOVASCULAR)
CIRCUITO_AMPLIO_CON_TENSION =  Ejercicio("CIRCUITO_AMPLIO_CON_TENSION", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.CARDIOVASCULAR)
HIDROTERAPIA_ALTA_TEMPERATURA =  Ejercicio("HIDROTERAPIA_ALTA_TEMPERATURA", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.RESPIRATORIA)
HIDROTERAPIA_BAJA_TEMPERATUERA =  Ejercicio("HIDROTERAPIA_BAJA_TEMPERATUERA", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.RESPIRATORIA)
FISIOTERAPIA_ACUATICA =  Ejercicio("FISIOTERAPIA_ACUATICA", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.RESPIRATORIA)
FISIOTERAPIA_ACUATICA_CON_TENSION =  Ejercicio("FISIOTERAPIA_ACUATICA_CON_TENSION", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.RESPIRATORIA)
HIDROTERAPIA_CON_MASAJE =  Ejercicio("HIDROTERAPIA_CON_MASAJE", TipoTerapia.REHABILITACION, TipoObjetivo.RECUPERACION_LESION_OSEA, Restriccion.RESPIRATORIA)

